# Generated by Django 4.0.3 on 2022-06-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_salesperson_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usaddress',
            name='state',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='UsAddress',
        ),
    ]
