# Generated by Django 4.0.3 on 2022-06-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_usaddress_state_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='sale_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_person', to='sales_rest.salesperson'),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='sales_price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
