# Generated by Django 4.0.3 on 2022-06-20 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.PositiveIntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='Pending', max_length=9)),
                ('vip', models.BooleanField(default=False)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='service_rest.technician')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceAppointment',
        ),
    ]
