# Generated by Django 4.0.3 on 2022-06-21 16:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
