# Generated by Django 4.0.3 on 2022-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_remove_service_time_alter_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autovo',
            name='vin',
            field=models.CharField(max_length=17),
        ),
    ]
